CREATE TABLE blog(
    blog_id INT GENERATED BY DEFAULT AS IDENTITY primary key ,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE blog_category(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    blog_id INT references blog(blog_id)
);

CREATE TABLE blog_paragraph(
    paragraph_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paragraph VARCHAR,
    blog_id INT references blog(blog_id)
);

CREATE TABLE blog_comment(
  comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment VARCHAR,
  blog_id INT references blog(blog_id)
);

CREATE TABLE blog_tag(
  tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag VARCHAR,
  blog_id INT references blog(blog_id)
);

CREATE TABLE blog_like(
   like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   count INT,
   blog_id INT references blog(blog_id)
);

INSERT INTO blog(title)
    VALUES ('Iphone 14 pro');
INSERT INTO blog_paragraph(paragraph, blog_id)
    VALUES('first description', 1);
INSERT INTO blog_category(name, blog_id)
    VALUES ('mobile phone', 1);
INSERT INTO blog_comment(comment, blog_id)
    VALUES ('cool', 1);
INSERT INTO blog_like(count, blog_id)
    VALUES (10, 1);
INSERT INTO blog_tag(tag, blog_id)
    VALUES ('Iphone 14', 1);
INSERT INTO blog_tag(tag, blog_id)
VALUES ('Iphone', 1);

SELECT blog_category.name from blog
    JOIN blog_category ON blog.blog_id = blog_category.blog_id