CREATE TABLE blog_categories(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE blog_paragraphs(
    paragraph_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paragraph VARCHAR
);

CREATE TABLE blog_comments(
   comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   comments VARCHAR
);

CREATE TABLE blog_tags(
   tag_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   tag VARCHAR
);

CREATE TABLE blog_likes(
   like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   count INT
);

CREATE TABLE blogs(
    blog_id INT GENERATED BY DEFAULT AS IDENTITY primary key ,
    title VARCHAR(100),
    category_id INT references blog_categories(category_id),
    paragraph_id INT references blog_paragraphs(paragraph_id),
    comment_id INT references blog_comments(comment_id),
    tag_id INT references blog_tags(tag_id),
    like_id INT references blog_likes(like_id),
    created_at TIMESTAMP
)